base_url = "https://deepthought-theme.netlify.app"
title = "DeepThought"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/docs", name = "Docs" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]}
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "DeepThought"
avatar = "/images/avatar.png"

[extra.social]
facebook = "RatanShreshtha"
github = "RatanShreshtha"
gitlab = "ratanshreshtha"
keybase = "RatanShreshtha"
linkedin = "ratanshreshtha"
stackoverflow = "3728911"
email = "deepthought@gmail.com"
twitter = "RatanShreshtha"

[extra.analytics]
google = "UA-176984489-2"

[extra.commenting]
hyvor = "1967"

[extra.mapbox]
access_token = "pk.eyJ1IjoicmF0YW5zaHJlc2h0aGEiLCJhIjoiY2tla2s2NmM3MDd0ZzJzbXFtc3Y2YmU0NyJ9.0RhUnJPKbxHWw3xGPnnBlA"
