name = "deep-thought"
description = "A simple blog theme focused on writing powered by Bulma and Zola."
license = "MIT"
homepage = "https://github.com/RatanShreshtha/deep-thought"
# The minimum version of Zola required
min_version = "0.9.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Ratan Kulshreshtha"
homepage = "https://ratanshreshtha.github.io/"
